language: php

php:
  - 7.4

#branches:
#  only:
#    - master

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit
